module.exports = {
    databaseService: require('./database'),
    dataGenService: require('./datagen.service'),
    surepassService: require('./surepass.service'),
    pinePerkService: require('./giftcard.pineperks.service'),
    qwikCilverService: require('./giftcard.qwikcilver.service'),
    kycService: require('./kyc.service'),
    commonService: require('./common.service'),
    emailService: require('./email.services'),
    authService: require('./auth.service'),
    rolesService: require('./user.role.service'),
    ticketService: require('./ticket.service'),
    userService: require('./users.service'),
    cardService: require('./card.service'),
    userProfileService: require('./user.profile.service'),
    userAddressService: require('./user.addresses.service'),
    userKycDetailsService: require('./user.kyc.details.service'),
    userTokenService: require('./user.token.service'),
    businessUserService: require('./business.user.services')
}